import numpy as np
import cv2
while (1):
    img = cv2.imread("1.png")
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    lower_red1 = np.array([0, 20, 20])
    upper_red1 = np.array([8, 255, 255])
    lower_red2 = np.array([165, 20, 20])
    upper_red2 = np.array([179, 255, 255])
    lower_orange = np.array([9, 20, 20])
    upper_orange = np.array([25, 255, 255])
    lower_yellow = np.array([26, 20, 20])
    upper_yellow = np.array([40, 255, 255])
    lower_green = np.array([41, 20, 20])
    upper_green = np.array([85, 255, 255])
    lower_blue = np.array([86, 20, 20])
    upper_blue = np.array([130, 255, 255])
    lower_purple = np.array([131, 20, 20])
    upper_purple = np.array([164, 255, 255])
    lower_white = np.array([0, 0, 0])
    upper_white = np.array([179, 19, 255])
    mask1_red = cv2.inRange(hsv, lower_red1, upper_red1)
    mask2_red = cv2.inRange(hsv, lower_red2, upper_red2)
    mask_orange = cv2.inRange(hsv, lower_orange, upper_orange)
    mask_yellow = cv2.inRange(hsv, lower_yellow, upper_yellow)
    mask_green = cv2.inRange(hsv, lower_green, upper_green)
    mask_blue = cv2.inRange(hsv, lower_blue, upper_blue)
    mask_purple = cv2.inRange(hsv, lower_purple, upper_purple)
    mask_white = cv2.inRange(hsv, lower_white, upper_white)
    red = cv2.bitwise_and(img, img, mask = mask1_red)+cv2.bitwise_and(img, img, mask = mask2_red)
    orange = cv2.bitwise_and(img, img, mask = mask_orange)
    yellow = cv2.bitwise_and(img, img, mask = mask_yellow)
    green = cv2.bitwise_and(img, img, mask = mask_green)
    blue = cv2.bitwise_and(img, img, mask = mask_blue)
    purple = cv2.bitwise_and(img, img, mask = mask_purple)
    white = cv2.bitwise_and(img, img, mask = mask_white)
    cv2.imshow('img', img)
    cv2.imshow('red', red)
    cv2.imshow('orange', orange)
    cv2.imshow('yellow', yellow)
    cv2.imshow('green', green)
    cv2.imshow('blue', blue)
    cv2.imshow('purple', purple)
    cv2.imshow('white', white)
    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break
cv2.destroyAllWindows()
